# MISSING: package-json- updates
# #Lints code pre-commit --- prevents error-code in repo
# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.6.0 
#     hooks:
#       - id: trailing-whitespace  # Removes trailing whitespace
#       - id: end-of-file-fixer     # Ensures files end with a newline
#       - id: check-yaml            # Checks YAML syntax
#       - id: check-added-large-files  # Prevents adding large files

#   - repo: https://github.com/pre-commit/mirrors-eslint
#     rev: v9.9.1  # ESLint-Version
#     hooks:
#       - id: eslint
#         args: ['--fix']
#         name: Lint JavaScript and TypeScript files
#         additional_dependencies:
#           - eslint-plugin-react
#           - eslint-plugin-react-hooks
#           - "@typescript-eslint/eslint-plugin"
#           - eslint-config-prettier
#         files: \.(js|jsx|ts|tsx)$

# #auto-format
#   - repo: https://github.com/pre-commit/mirrors-prettier
#     rev: v4.0.0  # Prettier-Version
#     hooks:
#       - id: prettier
#         args: ["--write", "."]

# #checks code on spells
#   - repo: https://github.com/streetsidesoftware/cspell
#     rev: v6.16.0  
#     hooks:
#       - id: cspell
#         args: ["--config", "cspell.json"]
  
# #checks type errors
#   - repo: https://github.com/pre-commit/mirrors-tsc
#     rev: v1.0.0
#     hooks:
#       - id: tsc
