---
name: Issue template
about: This template provides a basic structure for user story issues.

---

# User story
As a ..., I want to ..., so I can ...

# Acceptance criteria

- [ ] 

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified 

# Complexity
- [ ] XS
- [ ] S
- [ ] M
- [ ] L
- [ ] XL

